# Generated by Django 3.1.13 on 2021-11-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_auto_20211102_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='District')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beneficiary.district')),
            ],
        ),
    ]
